# Generated by Django 2.0.4 on 2018-04-15 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Registre su correo electrónico', max_length=254)),
                ('nombres', models.CharField(max_length=500)),
                ('apellidos', models.CharField(max_length=500)),
                ('telf', models.CharField(default='-', help_text='Número de teléfono móvil (opcional)', max_length=100)),
                ('sexo', models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Prefiero no decirlo', '-')], default='-', max_length=20)),
                ('grupo', models.CharField(default='-', help_text='Grupo o asociación a la que pertenece (Pude dejar en blanco)', max_length=300)),
                ('grado_academico', models.CharField(choices=[('Bachiller', 'Bachiller'), ('Técnico', 'Técnico'), ('Licenciatura', 'Licenciatura'), ('Magíster', 'Maǵister'), ('Doctor', 'Doctor'), ('Prefiero no indicar', '-')], default='-', help_text='Máximo grado académico alcanzado', max_length=300)),
                ('conoce_flisol', models.BooleanField(default=False)),
                ('conoce_sofware_libre', models.BooleanField(default=False)),
                ('usado_software_libre', models.BooleanField(default=False)),
                ('tipo_participacion', models.CharField(choices=[('Quiero que me ayuden a instalar software libre en mi computadora', 'asistente'), ('Como expositor con el tema:', 'expositor'), ('Ayudando en la instalación de software el día del FLISOL o capacitando a otros para ser instaladores', 'instalador'), ('Me gustaría una mesa para hablar de una tematica relacionada al software libre', 'mesa debate'), ('Quiero ayudar en la organización y logística del evento', 'logistica'), ('Otro', 'otro')], default=('Quiero que me ayuden a instalar software libre en mi computadora', 'asistente'), max_length=1000)),
                ('comentarios', models.CharField(default='-', help_text='Comentarios o sugerencias para la organización del evento', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParticipacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default=('Quiero que me ayuden a instalar software libre en mi computadora', 'asistente'), max_length=1000)),
                ('expositor', models.BooleanField(default=False)),
                ('expositor_software_manejado', models.CharField(default='-', help_text='Por favor indica algunos ejemplos del software libre que has manejado (y si gustas algunos ejemplos del uso que le has dado)', max_length=1000)),
                ('expositor_tema', models.CharField(default='-', help_text='Indica el tema que desea exponer', max_length=500)),
                ('asistente', models.BooleanField(default=False)),
                ('asistente_software_deseado', models.CharField(choices=[('Educativo', 'Educativo'), ('Para Internet', 'Para Internet'), ('Juegos', 'Juegos'), ('Multimadia', 'Multimedia'), ('Accesorios', 'Accesorios'), ('Diseño gráfico', 'Diseño gráfico'), ('Seguridad', 'Seguridad'), ('Oficina', 'Oficina'), ('Programación', 'Programación'), ('Científico', 'Científico'), ('Otro', 'Otro')], default=('Educativo', 'Educativo'), max_length=500)),
                ('asistente_otro_desc', models.CharField(default='-', max_length=500)),
                ('instalador', models.BooleanField(default=False)),
                ('instalador_capacitacion', models.BooleanField(default=True, help_text='Requeriré capacitación para para ayudar como instalador')),
                ('instalador_tipo_software', models.CharField(choices=[('Sistemas Operativos libres para PC', 'Sistemas Operativos libres para PC'), ('Sistemas Operativos libres para Moviles', 'Sistemas Operativos libres para Moviles'), ("Programas libres para diferentes temáticas (favor describir que temáticas o programas en la opción 'Otros')", 'Programas libres para diferentes temáticas'), ('Otro', 'Otro')], default=('Sistemas Operativos libres para PC', 'Sistemas Operativos libres para PC'), help_text='Indica el tipo de software que nos podrías ayudar a instalar', max_length=500)),
                ('logistica', models.BooleanField(default=False)),
                ('logistica_tipo', models.CharField(choices=[('Apoyo logístico en la organización y gestión del evento.', 'Apoyo logístico en la organización y gestión del evento.'), ('Difusión en redes sociales', 'Difusión en redes sociales'), ('Difusión en prensa y otros medios de comunicación', 'Difusión en prensa y otros medios de comunicación'), ('Difusión en prensa y otros medios de comunicación', 'Difusión en prensa y otros medios de comunicación'), ('Otro', 'Otro')], max_length=500)),
                ('logistica_otro_desc', models.CharField(default='-', max_length=1000)),
                ('participante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form.Participante')),
            ],
        ),
    ]
