# Generated by Django 2.0.4 on 2018-04-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20180415_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='usado_software_libre',
        ),
        migrations.AddField(
            model_name='participante',
            name='ha_usado_software_libre',
            field=models.BooleanField(default=False, help_text='(Marque si ha usado software libre)'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='conoce_flisol',
            field=models.BooleanField(default=False, help_text='(Marque si sabe que es el FLISOL)'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='conoce_software_libre',
            field=models.BooleanField(default=False, help_text='(Marque si conoce el Software Libre)'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tipo_participacion',
            field=models.CharField(choices=[('Quiero que me ayuden a instalar software libre en mi computadora', 'asistente'), ('Como expositor con el tema:', 'expositor'), ('Ayudando en la instalación de software el día del FLISOL o capacitando a otros para ser instaladores', 'instalador'), ('Me gustaría una mesa para hablar de una tematica relacionada al software libre', 'mesa debate'), ('Quiero ayudar en la organización y logística del evento', 'logistica'), ('Otro', 'otro')], default=('Quiero que me ayuden a instalar software libre en mi computadora', 'asistente'), help_text='Seleccione la forma en la que desea participar', max_length=1000),
        ),
    ]
