# Generated by Django 2.0.4 on 2018-04-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20180415_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoparticipacion',
            name='otro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoparticipacion',
            name='otro_desc',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='participante',
            name='comentarios',
            field=models.CharField(default=' ', help_text='Comentarios o sugerencias para la organización del evento', max_length=1000),
        ),
        migrations.AlterField(
            model_name='participante',
            name='conoce_el_flisol',
            field=models.BooleanField(default=False, help_text='¿Sabe que es el FLISOL?'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='conoce_el_software_libre',
            field=models.BooleanField(default=False, help_text='¿Conoce el Software Libre?'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='grado_academico',
            field=models.CharField(choices=[('Bachiller', 'Bachiller'), ('Técnico', 'Técnico'), ('Licenciatura', 'Licenciatura'), ('Magíster', 'Maǵister'), ('Doctor', 'Doctor'), ('Prefiero no indicar', '-')], default='prefiero no especificar', help_text='Máximo grado académico alcanzado', max_length=300),
        ),
        migrations.AlterField(
            model_name='participante',
            name='grupo',
            field=models.CharField(default=' ', help_text='Grupo o asociación a la que pertenece (Pude dejar en blanco)', max_length=300),
        ),
        migrations.AlterField(
            model_name='participante',
            name='ha_usado_software_libre',
            field=models.BooleanField(default=False, help_text='¿Ha usado software libre?'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='sexo',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Prefiero no decirlo', 'prefiero no decirlo')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telf',
            field=models.CharField(default=' ', help_text='Número de teléfono móvil (opcional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tipo_de_participacion',
            field=models.CharField(choices=[('Quiero que me ayuden a instalar software libre en mi computadora', 'Sólo asistir'), ('Como expositor con el tema:', 'Exponer un tema'), ('Ayudando en la instalación de software el día del FLISOL o capacitando a otros para ser instaladores', 'Instalador'), ('Me gustaría una mesa para hablar de una tematica relacionada al software libre', 'Mesa de debate'), ('Quiero ayudar en la organización y logística del evento', 'Logística'), ('Otro', 'otro')], default=('Quiero que me ayuden a instalar software libre en mi computadora', 'Sólo asistir'), help_text='Seleccione la forma en la que desea participar', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='asistente_otro_desc',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='expositor_software_manejado',
            field=models.CharField(default=' ', help_text='Por favor indica algunos ejemplos del software libre que has manejado (y si gustas algunos ejemplos del uso que le has dado)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='expositor_tema',
            field=models.CharField(default=' ', help_text='Indica el tema que desea exponer', max_length=500),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='logistica_otro_desc',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='tipo',
            field=models.CharField(default=('Quiero que me ayuden a instalar software libre en mi computadora', 'Sólo asistir'), max_length=1000),
        ),
    ]
