# Generated by Django 2.0.1 on 2018-08-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20180415_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='comentarios',
            field=models.CharField(blank=True, default=' ', help_text='Comentarios o sugerencias para la organización del evento', max_length=1000),
        ),
        migrations.AlterField(
            model_name='participante',
            name='grupo',
            field=models.CharField(blank=True, default=' ', help_text='Grupo o asociación a la que pertenece (Pude dejar en blanco)', max_length=300),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telf',
            field=models.CharField(blank=True, default=' ', help_text='Número de teléfono móvil (opcional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='asistente_otro_desc',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='expositor_software_manejado',
            field=models.CharField(blank=True, default=' ', help_text='Por favor indica algunos ejemplos del software libre que has manejado (y si gustas algunos ejemplos del uso que le has dado)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='expositor_tema',
            field=models.CharField(blank=True, default=' ', help_text='Indica el tema que desea exponer', max_length=500),
        ),
        migrations.AlterField(
            model_name='tipoparticipacion',
            name='logistica_otro_desc',
            field=models.CharField(blank=True, default=' ', max_length=1000),
        ),
    ]
